### ISSUE TITLE
cross platform chat message not received properly

### ISSUE THREAD

**Issue by RaysonYeungHK** [QuickBlox/quickblox-android-sdk-releases#12]
Android SDK Version: 3.3.3
iOS SDK Version: 2.9.2

Testing environment:
Android 6.0
iOS 10.3.1

Tested Cases
1. Android -> Android : create chat message via QBRestChatService, success
2. iOS -> iOS : create chat message via QBRequest createMessage, success
3. Android -> iOS : create chat message via QBRestChatService, success
4. iOS -> Android : create chat message via QBRequest createMessage, failed

Found:
iOS send "A" at time "10" to Android, android didn't get any callback from QBChatDialogMessageListener
iOS send "B" at time "20" to Android, android receive callback from QBChatDialogMessageListener with message "A" and time "20"
iOS send "C" at time "35" to Android, android didn't get any callback from QBChatDialogMessageListener
iOS send "D" at time "50" to Android, android receive callback from QBChatDialogMessageListener with message "C" and time "35"

**Comment by avani-digital** [comment]
I am also having the same issue.

**Comment by tatanka987** [comment]
its happened because you set empty parameter to additional parameters, this bug was fixed in version 3.5.1
