### ISSUE TITLE
issue in build.gradle 

### ISSUE THREAD

**Issue by jatinbsa** [QuickBlox/quickblox-android-sdk-releases#14]
this error come when import this project 
  Error:(29, 13) Failed to resolve: com.quickblox:quickblox-android-sdk-chat:3.4.0 

please tell me the solution as soon as if it possible

**Comment by ghost** [comment]
Use def `qbSdkVersion = '3.4'` instead of def `qbSdkVersion = '3.4.0'`

**Comment by RomanPronin** [comment]
Closed, as resolved.
