### ISSUE TITLE
Gradle 7.0.2

### ISSUE THREAD

**Issue by AnuragNegiAndroid** [QuickBlox/quickblox-android-sdk-releases#25]
Hi
I upgraded my gradle to com.android.tools.build:gradle:7.0.2 after that I am getting an error
Could not find org.webrtc:google-webrtc:1.0.25003.
Required by:
    project :app > com.quickblox:quickblox-android-sdk-videochat-webrtc:3.9.11

**Comment by ghost** [comment]
@AnuragNegiAndroid Hello,

This is Nikolay from QuickBlox support.

I have just updated gradle and ran an application. 
There is no issue with org.webrtc:google-webrtc:1.0.25003 on my end.
You may check the attached screenshots.

Please try checking our Android WebRTC samples:
https://docs.quickblox.com/docs/code-samples#video-calling-samples
![2022-01-05_12-21](https://user-images.githubusercontent.com/88783425/148207261-fbde4013-8016-49df-835c-2f34043d6da2.png)
![2022-01-05_12-55](https://user-images.githubusercontent.com/88783425/148207280-2a68d4d3-e519-4d71-bff5-c0e93253b315.png)
)

**Comment by AnuragNegiAndroid** [comment]
Hi @QB-nikolay-zolotarov ,
I think this issue came when I replaced jcenter() to mavencentrel(), as jcenter is deprecated.

**Comment by RuslanKharkevych** [comment]
Hi @QB-nikolay-zolotarov,
I am getting the same issue when I'm trying to migrate from [deprecated JCenter](https://blog.gradle.org/jcenter-shutdown) to Maven Central.
Is there a workaround or we are still obliged to use JCenter repository?

**Comment by ghost** [comment]
@AnuragNegiAndroid @RuslanKharkevych Thank you for the information.

 According to our developers, it is required to keep jcenter() in the project.
