### ISSUE TITLE
android permission .BLUETOOTH_CONNECT

### ISSUE THREAD

**Issue by AKAlahmed** [QuickBlox/quickblox-android-sdk-releases#28]
Hi every one 
I have an issue when I try to start Voice Call, it's telling me to add Bluetooth connect permission and I added it in manifest but  I still getting this error on android 12 only

> E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.saatco.murshadik, PID: 1820
>     java.lang.RuntimeException: Unable to create service com.saatco.murshadik.fcm.CallService: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@9c2035c3: getName
>         at android.app.ActivityThread.handleCreateService(ActivityThread.java:4500)
>         at android.app.ActivityThread.access$1700(ActivityThread.java:247)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2072)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loopOnce(Looper.java:201)
>         at android.os.Looper.loop(Looper.java:288)
>         at android.app.ActivityThread.main(ActivityThread.java:7839)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
>      Caused by: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for android.content.AttributionSource@9c2035c3: getName
>         at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
>         at android.os.Parcel.createException(Parcel.java:2409)
>         at android.os.Parcel.readException(Parcel.java:2392)
>         at android.os.Parcel.readException(Parcel.java:2334)
>         at android.bluetooth.IBluetoothManager$Stub$Proxy.getName(IBluetoothManager.java:802)
>         at android.bluetooth.BluetoothAdapter.getName(BluetoothAdapter.java:1297)
>         at com.quickblox.videochat.webrtc.AppRTCBluetoothManager.logBluetoothAdapterInfo(AppRTCBluetoothManager.java:435)
>         at com.quickblox.videochat.webrtc.AppRTCBluetoothManager.start(AppRTCBluetoothManager.java:261)
>         at com.quickblox.videochat.webrtc.AppRTCAudioManager.start(AppRTCAudioManager.java:277)
>         at com.saatco.murshadik.fcm.CallService.initAudioManager(CallService.java:414)
>         at com.saatco.murshadik.fcm.CallService.onCreate(CallService.java:134)
>         at android.app.ActivityThread.handleCreateService(ActivityThread.java:4487)
>         at android.app.ActivityThread.access$1700(ActivityThread.java:247) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2072) 
>         at android.os.Handler.dispatchMessage(Handler.java:106) 
>         at android.os.Looper.loopOnce(Looper.java:201) 
>         at android.os.Looper.loop(Looper.java:288) 
>         at android.app.ActivityThread.main(ActivityThread.java:7839) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
>      Caused by: android.os.RemoteException: Remote stack trace:
>         at com.android.server.BluetoothManagerService.checkPermissionForDataDelivery(BluetoothManagerService.java:2918)
>         at com.android.server.BluetoothManagerService.checkConnectPermissionForDataDelivery(BluetoothManagerService.java:2936)
>         at com.android.server.BluetoothManagerService.getName(BluetoothManagerService.java:1737)
>         at android.bluetooth.IBluetoothManager$Stub.onTransact(IBluetoothManager.java:380)
>         at android.os.Binder.execTransactInternal(Binder.java:1179)

**Comment by ghost** [comment]
@ameen95195 Hello,

This is Nikolay from QuickBlox support.

Please check this thread:
https://stackoverflow.com/questions/67722950/android-12-new-bluetooth-permissions

**Comment by AKAlahmed** [comment]
Thanx a lot !!!
